---
- name: Make sure that directory exists
  file: 
    state: directory
    mode: '0755'
    path: /etc/opt/oci-hpc


- name: create tcp hostfile
  template:
    src: templates/hostfile_tcp.j2
    dest: /tmp/hostfile.tcp
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: hostfile
  delegate_to: 127.0.0.1
  run_once: true


- name: Copy to all hosts
  copy: 
    src: /tmp/hostfile.tcp
    dest: /etc/opt/oci-hpc/hostfile.tcp

   
- name: Create a symbolic link
  file:
    src: "/etc/opt/oci-hpc/{{ item }}"
    dest: /etc/opt/oci-hpc/hostfile
    owner: root
    group: root
    state: link
    mode: '0644'
  with_items: 
    - "hostfile.tcp"

- name: delete /tmp/hostfile.tcp
  file: 
    path: /tmp/hostfile.tcp
    state: absent 



