

- hosts: all
  become: true
  vars: 
    destroy: false
    initial: true
  gather_facts: true
  roles: 
    - oci-cloud-agent
#    - packages
    - firewall
    - oci-hostname
    - ssh
    - limits
    - mpi-hostfiles
    - etc-hosts


- hosts: bastion
  become: true
  tasks: 
    - include_role: 
        name: passwords
      
- hosts: all
  become: true
  tasks:
    - include_role:
        name: nfs-client
      vars:
        local_path: "{{ nfs_target_path }}"
        export_host: "{{ nfs_source_IP }}"
        export_path: "{{ nfs_source_path }} "
        options: "{{ nfs_options }}"
        lock: "none"
      when: add_nfs|default(false)|bool



- hosts: compute
  become: true
  tasks:
    - include_role:
        name: nfs-client
      vars:
        local_path: "{{ source_fs_local_mount_path }}"
        export_host: "{{ source_fs_server_ip }}"
        export_path: "{{ source_fs_server_exported_path }} "
        options: "{{ source_fs_options }}"
        lock: "none"
      when: posix_2_posix|default(false)|bool or posix_2_os|default(false)|bool


- hosts: compute
  become: true
  tasks:
    - include_role:
        name: nfs-client
      vars:
        local_path: "{{ destination_fs_local_mount_path }}"
        export_host: "{{ destination_fs_server_ip }}"
        export_path: "{{ destination_fs_server_exported_path }} "
        options: "{{ destination_fs_options }}"
        lock: "none"
      when: os_2_posix|default(false)|bool


- hosts: compute
  tasks:
    - include_role:
        name: source-fs
      when: posix_all_tools|default(false)|bool or fpsync|default(false)|bool
    - include_role:
        name: destination-fs
      when: posix_all_tools|default(false)|bool or fpsync|default(false)|bool
    - include_role:
        name: fpsync-shared-fs
      when: posix_all_tools|default(false)|bool or fpsync|default(false)|bool
    - include_role:
        name: fpsync
      when: posix_all_tools|default(false)|bool or fpsync|default(false)|bool


- hosts: compute
  tasks:
    - include_role:
        name: oci-file-transfer
      when: posix_all_tools|default(false)|bool



- hosts: compute
  tasks:
    - include_role:
        name: oci-file-transfer
      when: oci_parallel_transfer_tools|default(false)|bool
      

- hosts: compute
  tasks:
    - include_role:
        name: rclone
      when: os_all_tools|default(false)|bool
    - include_role:
        name: s5cmd
      when: os_all_tools|default(false)|bool
    - include_role:
        name: oci-cli
      when: os_all_tools|default(false)|bool


- hosts: compute
  tasks:
    - include_role:
        name: rclone
      when: rclone|default(false)|bool

- hosts: compute
  tasks:
    - include_role:
        name: s5cmd
      when: s5cmd|default(false)|bool


- hosts: compute
  tasks:
    - include_role:
        name: oci-cli
      when: oci_cli|default(false)|bool


# generate sample script to show how to run migration. Common for all tools.
- hosts: compute
  tasks:
    - include_role:
        name: generate-migrate-command


- hosts: bastion
  become: true
  tasks:
    - include_role:
        name: prometheus
      when: monitoring|default(false)|bool
    - include_role:
        name: grafana
      when: monitoring|default(false)|bool




# deploy prometheus node exporter on all nodes
- hosts: compute,bastion
  roles:
    - cloudalchemy.node_exporter
